SELECT COORDINATES FROM AIRPORTS WHERE ICAO = 'LOWW';

SELECT * FROM PUBLIC.AIRPORTS WHERE ISO_COUNTRY = 'AR';

SELECT * FROM PUBLIC.AIRPORTS;

SELECT ISO_COUNTRY FROM AIRPORTS WHERE ICAO = 'LOWW';

SELECT ICAO FROM AIRPORTS WHERE ISO_COUNTRY = 'HR';
SELECT ICAO, NAME, ISO_COUNTRY, COORDINATES FROM AIRPORTS WHERE ISO_COUNTRY = 'HR';